# -*- coding: utf-8 -*-
"""灰机标准 300 条 RAG 测试集 —— 候选题池。

候选题三类来源（均为确定性生成，无随机）：
  1. SEEDS：scripts/eval_rag_huiji.py 的 14 题 seed（q/ref/evidence 原样保留）；
  2. HAND ：人工阅读语料（plot_corpus_wu_ming_zhe.json）与 lore 出题，证据词
            均经过语料命中预检（英文 ASR 名词为准，中英文备选）；
  3. AUTO ：由 data/lore/wu_ming_zhe/plot_aliases.json 的正名→别名表自动生成
            的中英译名题（过滤代词/单字/The 前缀噪声）。

字段格式与 gen_rag_testset_300.py 约定一致：
  q / ref / evidence（组内互为备选；组1=答案词，组2+=题干限定词）
  dims.type  : factoid | multi-hop | reasoning | temporal
  dims.hop   : single | multi
  dims.chapter : 1.4 | 1.7 | 1.9 | 1971 | 其他   （1.4=洞穴的囚徒，1.7=今夜星光
                 灿烂，1.9=孤独之歌，1971=绿湖噩梦，其余含联动归"其他"）
  difficulty / depth / text_len 由 gen 脚本按确定性规则补齐（也可显式覆盖）。

由 gen_rag_testset_300.py import 使用；本文件不产生任何副作用（只读语料表）。
"""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# ── 构造辅助 ────────────────────────────────────────────────────────────────

def _c(q: str, ref: str, evidence: list, type_: str = "factoid",
       hop: str | None = None, chapter: str = "其他",
       difficulty: str | None = None, depth: str | None = None,
       source: str = "generated") -> dict:
    """构造一条候选题（hop/difficulty/depth 缺省时由 gen 脚本按规则补齐）。"""
    dims: dict = {"type": type_, "chapter": chapter}
    if hop:
        dims["hop"] = hop
    if difficulty:
        dims["difficulty"] = difficulty
    if depth:
        dims["depth"] = depth
    return {"q": q, "ref": ref, "evidence": evidence, "dims": dims,
            "source": source}


# ── 1. SEED 题（14 条，q/ref/evidence 与 eval_rag_huiji.py 完全一致）────────

SEEDS = [
    _c("薇洛的真名是什么？",
       "Charlotte O'Hagan（伦敦十字街女巫，前乌卢鲁运动会最年轻金牌得主）",
       [["Charlotte", "夏洛蒂", "夏洛特", "奥哈根"]],
       chapter="1.4", source="seed"),
    _c("可燃点体内的火到底是什么？",
       "乌卢鲁圣火，本体为 Ulu（和平乌鲁）",
       [["Ulu", "和平乌鲁"], ["圣火", "火种", "火焰", "fire"]],
       chapter="其他", source="seed"),
    _c("旧金山海特街的疗愈师是谁？",
       "环状水星（Mercuria），兼迪厅舞女",
       [["环状水星", "Mercuria"]],
       chapter="其他", source="seed"),
    _c("J 的义妹是谁？",
       "保利娜·勒萨奇（Paulina），原圣洛夫基金会调查员，第二次暴雨中被回溯而死",
       [["保利娜", "Paulina"]],
       chapter="其他", source="seed"),
    _c("雷米特杯失窃案里 Melania 的保安公司叫什么？",
       "拉米雷斯保安公司（Ramirez security company）",
       [["拉米雷斯", "Ramirez", "雷米雷斯"]],
       chapter="其他", source="seed"),
    _c("《神秘警探C07》三部曲的导演是谁？",
       "菲林士多（Noire），中国香港导演",
       [["菲林士多", "Noire"], ["C07", "神秘警探"]],
       chapter="其他", source="seed"),
    _c("《疯癫与文明》里那座巨型监狱叫什么？",
       "科马拉（Komala），全景监狱",
       [["科马拉", "Komala", "全景监狱"]],
       chapter="其他", source="seed"),
    _c("虚构集的小说《理性家族的崛起与衰落》的故事发生地是哪里？",
       "阿马尔菲塔诺（Amalfitano，取自波拉尼奥《2666》人名）",
       [["阿马尔菲塔诺", "Amalfitano"]],
       chapter="其他", source="seed"),
    _c("卡卡尼亚的本名是什么？",
       "克拉拉·温格勒（Klara Vingler），维也纳精神科医学生",
       [["克拉拉", "Clara", "温格勒"]],
       chapter="1.7", source="seed"),
    _c("维也纳篇与卡卡尼亚对峙决斗的医生是谁？",
       "施瓦茨医生（Dr. Schwartz，以电击治疗骗财）",
       [["施瓦茨", "Schwartz"]],
       chapter="1.7", source="seed"),
    _c("海因里希最后被谁杀死？",
       "被叛变的伊索尔德开枪击毙",
       [["海因里希", "Heinrich"], ["伊索尔德", "Isolde"]],
       chapter="1.7", source="seed"),
    _c("自由海风号邮轮的音乐总监是谁？",
       "芭卡洛儿·斯特拉迪瓦里（Barcarola Stradivari），克雷莫纳人",
       [["芭卡洛儿", "Barcarola", "斯特拉迪瓦里"]],
       chapter="其他", source="seed"),
    _c("努库泰澳的岛民都有谁？",
       "图图石子（Fatutu）、托阿（Toa）、塞洛尼（Selone）、卡穆塔（Kamuta）",
       [["图图石子", "Tutu", "Fatutu"], ["托阿", "Toa"],
        ["塞洛尼", "Salone", "Selone", "卡穆塔", "Kamuta"]],
       chapter="其他", source="seed"),
    _c("在中央塔里自囚的医生是谁？",
       "阿莱夫（Aleph，碎裂品所属，2.6 主线 BOSS 形态）",
       [["阿莱夫", "Aleph"], ["中央塔", "自囚", "central tower"]],
       chapter="其他", source="seed"),
]


# ── 2. 人工出题（HAND）────────────────────────────────────────────────────
# 证据词均以 ASR 语料实际写法为准（英文原名为主，中文备选），并经过预检。

HAND: list[dict] = []

# —— 1.9 孤独之歌（阿派朗岛 / 37）——
HAND += [
    _c("阿派朗岛上那位以数字命名的少女是谁？",
       "37（数字命名的神秘学家，阿派朗岛居民）",
       [["37"]], chapter="1.9"),
    _c("37 所居住的、完全不受暴雨影响的岛屿叫什么名字？",
       "阿派朗岛（Apeiron）",
       [["Apeiron", "阿派朗"]], chapter="1.9"),
    _c("阿派朗岛上的时间停滞在哪一年？",
       "2007 年",
       [["2007"]], type_="temporal", chapter="1.9"),
    _c("维尔汀在阿派朗岛击败阿尔卡纳之后获得的、能庇护更多人的道具是什么？",
       "平衡伞（umbrella）",
       [["umbrella"]], chapter="1.9"),
    _c("阿尔卡纳在大限将至时推举谁接任重塑之手的新领袖？",
       "苏菲亚（Sophia）",
       [["Sophia", "苏菲亚"]], type_="multi-hop", hop="multi", chapter="1.9"),
    _c("阿尔卡纳最终死于哪种轰炸武器？",
       "真空弹（vacuum bomb）",
       [["vacuum"]], chapter="1.9"),
    _c("孤独之歌篇里阿派朗岛的研究者乌尔里希的英文名是什么？",
       "Ulrich（乌尔里希）",
       [["Ulrich"]], chapter="1.9"),
    _c("孤独之歌篇里出现的露西的英文名是什么？",
       "Lucy（露西）",
       [["Lucy"]], chapter="1.9"),
    _c("重塑之手首领盯上的、盛产非对称核素 R 的岛屿是哪座？",
       "阿派朗岛（Apeiron）",
       [["Apeiron", "阿派朗"], ["Manus", "重塑之手"]],
       type_="multi-hop", hop="multi", chapter="1.9"),
    _c("岛上时间停留在 2007 年且未被暴雨回溯，据此推断这座与世隔绝的小岛是哪里？",
       "阿派朗岛（Apeiron）",
       [["Apeiron", "阿派朗"], ["2007"]], type_="reasoning", chapter="1.9"),
    _c("37 的同伴中，以数字六为名的少女叫什么？",
       "Six（六）",
       [["Six"]], chapter="1.9"),
    _c("阿德勒的英文名是什么？（孤独之歌篇）",
       "Adler（阿德勒）",
       [["Adler"]], chapter="1.9"),
    _c("维尔汀为防止 37 被暴雨回溯，带她离开了哪里？",
       "阿派朗岛（Apeiron）",
       [["Apeiron", "阿派朗"], ["37"]],
       type_="multi-hop", hop="multi", chapter="1.9"),
    _c("杀死阿尔卡纳的行动中，与基金会配合作战的军备学院是哪家？",
       "芝诺军备学院（Zeno）",
       [["Zeno", "芝诺"], ["Arcana", "阿尔卡纳"]],
       type_="multi-hop", hop="multi", chapter="1.9"),
    _c("根据曾指挥真空弹轰炸、使重塑之手首领灰飞烟灭的这一战，推断这位首领是谁？",
       "阿尔卡纳（Arcana）",
       [["Arcana", "阿尔卡纳"], ["vacuum"]],
       type_="reasoning", chapter="1.9"),
    _c("阿派朗岛与下面哪个英文名对应？",
       "Apeiron（阿派朗）",
       [["Apeiron"]], chapter="1.9"),
    _c("孤独之歌这个篇章名，与哪位独自留守海岛、钻研数学的数字少女有关？",
       "37（孤独之歌的阿派朗岛少女）",
       [["37"], ["Apeiron", "阿派朗"]], type_="reasoning", chapter="1.9"),
    _c("乌尔里希与 37 同样生活在哪座岛屿上？",
       "阿派朗岛（Apeiron）",
       [["Apeiron", "阿派朗"], ["Ulrich", "乌尔里希"]],
       type_="multi-hop", hop="multi", chapter="1.9"),
]

# —— 1.7 今夜星光灿烂（维也纳）——
HAND += [
    _c("今夜星光灿烂篇中红极一时的维也纳女演员是谁？",
       "伊索尔德（Isolde）",
       [["Isolde", "伊索尔德"], ["Vienna", "维也纳"]], chapter="1.7"),
    _c("伊索尔德最后开枪击毙了谁？",
       "海因里希（Heinrich）",
       [["Heinrich", "海因里希"], ["Isolde", "伊索尔德"]],
       type_="multi-hop", hop="multi", chapter="1.7"),
    _c("今夜星光灿烂篇的故事发生在哪座城市？",
       "维也纳（Vienna）",
       [["Vienna", "维也纳"]], chapter="1.7"),
    _c("今夜星光灿烂篇里的年轻调查员马库斯的英文名是什么？",
       "Marcus（马库斯）",
       [["Marcus"]], chapter="1.7"),
    _c("特奥菲尔的英文名是什么？（维也纳篇）",
       "Teofil（特奥菲尔）",
       [["Teofil"]], chapter="1.7"),
    _c("效忠于重塑之手、最终被伊索尔德枪杀的男人是谁？",
       "海因里希（Heinrich）",
       [["Heinrich", "海因里希"], ["Manus", "重塑之手"]],
       type_="multi-hop", hop="multi", chapter="1.7"),
    _c("本名克拉拉·温格勒的维也纳医生是谁？",
       "卡卡尼亚（Kakania）",
       [["Kakania", "卡卡尼亚"], ["Clara", "克拉拉"]],
       type_="multi-hop", hop="multi", chapter="1.7"),
    _c("以电击治疗骗财、与卡卡尼亚对峙的医生是谁？",
       "施瓦茨医生（Dr. Schwartz）",
       [["Schwartz", "施瓦茨"], ["Kakania", "卡卡尼亚"]], chapter="1.7"),
    _c("格蕾塔·霍夫曼的英文名是什么？（今夜星光灿烂篇）",
       "Greta Hofmann（格蕾塔·霍夫曼）",
       [["Greta", "Hofmann", "格蕾塔", "霍夫曼"]], chapter="1.7"),
    _c("今夜星光灿烂篇里出现的「血痛」概念英文叫什么？",
       "bloody pain（血痛）",
       [["bloody pain"]], chapter="1.7"),
    _c("根据她在维也纳行动、且本姓温格勒这两点，可以推断这位精神科医生是谁？",
       "卡卡尼亚（Kakania）",
       [["Kakania", "卡卡尼亚"], ["Vienna", "维也纳"]],
       type_="reasoning", chapter="1.7"),
    _c("多里斯医生的英文名是什么？",
       "Doris（多里斯）",
       [["Doris", "多里斯"]], chapter="1.7"),
    _c("卡卡尼亚的英文名是什么？",
       "Kakania（卡卡尼亚）",
       [["Kakania"]], chapter="1.7"),
    _c("马库斯与特奥菲尔同样活跃于哪座城市的故事里？",
       "维也纳（Vienna，今夜星光灿烂篇）",
       [["Vienna", "维也纳"], ["Marcus"]],
       type_="multi-hop", hop="multi", chapter="1.7"),
    _c("伊索尔德与海因里希的爱恨纠葛发生在哪个篇章？",
       "今夜星光灿烂（1.7 维也纳篇）",
       [["Isolde", "伊索尔德"], ["Heinrich", "海因里希"]],
       type_="multi-hop", hop="multi", chapter="1.7"),
]

# —— 1971 绿湖噩梦 ——
HAND += [
    _c("绿湖噩梦篇里驻扎在营地、负责孩子们健康的牙医是谁？",
       "牙仙（Tooth Fairy）",
       [["Tooth Fairy", "牙仙"], ["camp", "营地"]],
       type_="multi-hop", hop="multi", chapter="1971"),
    _c("绿湖噩梦篇的故事发生地是哪个营地？",
       "绿湖营地（Green Lake camp）",
       [["Green Lake", "绿湖"]], chapter="1971"),
    _c("绿湖营地的传说中，森林里出没的怪物是什么？",
       "巨怪（troll）",
       [["troll", "巨怪"], ["Green Lake", "camp"]], chapter="1971"),
    _c("绿湖噩梦中痴迷恐怖片的男孩的英文名是什么？",
       "Horropedia（恐怖片迷）",
       [["Horropedia"]], chapter="1971"),
    _c("洁西卡的英文名是什么？（绿湖噩梦篇）",
       "Jessica（洁西卡）",
       [["Jessica"]], chapter="1971"),
    _c("迈克尔的英文名是什么？（绿湖噩梦篇）",
       "Michael（迈克尔）",
       [["Michael"]], chapter="1971"),
    _c("弗莱迪的英文名是什么？（绿湖噩梦篇）",
       "Freddy（弗莱迪）",
       [["Freddy"]], chapter="1971"),
    _c("冷周六的英文名是什么？（绿湖噩梦篇登场角色）",
       "Hissabeth（冷周六）",
       [["Hissabeth"]], chapter="1971"),
    _c("根据营地医生以牙科医疗见长的设定，推断绿湖营地的医生是谁？",
       "牙仙（Tooth Fairy）",
       [["Tooth Fairy", "牙仙"], ["Green Lake", "camp"]],
       type_="reasoning", chapter="1971"),
    _c("绿湖噩梦篇里孩子们口中的怪物传说与哪座营地有关？",
       "绿湖营地（Green Lake camp）",
       [["Green Lake", "绿湖"], ["troll", "巨怪"]],
       type_="multi-hop", hop="multi", chapter="1971"),
    _c("绿湖噩梦篇的故事发生在哪一年？",
       "1971 年",
       [["1971"]], type_="temporal", chapter="1971"),
    _c("洁西卡与弗莱迪同为哪个营地的孩子？",
       "绿湖营地（Green Lake camp）",
       [["Jessica"], ["Freddy"]],
       type_="multi-hop", hop="multi", chapter="1971"),
    _c("牙仙与冷周六同属哪个篇章？",
       "绿湖噩梦（1.2，即 1971 年绿湖事件）",
       [["Tooth Fairy", "牙仙"], ["Hissabeth"]],
       type_="multi-hop", hop="multi", chapter="1971"),
    _c("巨怪传说与失踪案发生在哪一年的绿湖？",
       "1971 年（绿湖噩梦）",
       [["troll", "巨怪"], ["1971"]], chapter="1971"),
    _c("绿湖噩梦篇的孩子们在森林里遭遇了什么怪物？",
       "巨怪（troll）",
       [["troll", "巨怪"], ["woods", "forest", "森林"]], chapter="1971"),
]

# —— 1.4 洞穴的囚徒 ——
HAND += [
    _c("洞穴的囚徒篇里苏芙比买下的船叫什么名字？",
       "Rockin' Apple（摇滚苹果号）",
       [["Rockin"], ["Sotheby", "苏芙比"]],
       type_="multi-hop", hop="multi", chapter="1.4"),
    _c("洞穴的囚徒篇中被称作 standkeeper 的女性是谁？",
       "Zanetta（扎内塔）",
       [["Zanetta"]], chapter="1.4"),
    _c("一直跟随星锑的苹果形伙伴叫什么名字？",
       "APPLe（苹果）",
       [["APPLe", "Apple"], ["Regulus", "星锑"]],
       type_="multi-hop", hop="multi", chapter="1.4"),
    _c("洞穴的囚徒篇里海盗船上的歌手是谁？",
       "星锑（Regulus）",
       [["Regulus", "星锑"]], chapter="1.4"),
    _c("维尔汀一行在洞穴的囚徒篇里乘船前往的目的地是哪座岛？",
       "阿派朗岛（Apeiron）",
       [["Apeiron", "阿派朗"], ["ship", "船"]],
       type_="multi-hop", hop="multi", chapter="1.4"),
    _c("笃笃骨的真名是什么？",
       "Charlotte O'Hagan（伦敦十字街女巫）",
       [["Charlotte", "O'Hagan"]], chapter="1.4"),
    _c("伦敦十字街的雾中女巫是谁？",
       "薇洛（Willow，真名 Charlotte O'Hagan）",
       [["Charlotte", "Willow"], ["fog", "雾"]],
       type_="reasoning", chapter="1.4"),
    _c("洞穴的囚徒篇的故事主要发生在什么载具上？",
       "Rockin' Apple 号船（ship）",
       [["Rockin", "ship"]], chapter="1.4"),
    _c("洞穴的囚徒篇里保利娜也随行登场，她的英文名是什么？",
       "Paulina（保利娜）",
       [["Paulina"], ["Sotheby", "Regulus"]], chapter="1.4"),
    _c("洞穴的囚徒篇里的滚鳄书店英文名是什么？",
       "Rolling Croc Bookstore（滚鳄书店）",
       [["Rolling Croc", "滚鳄"]], chapter="1.4"),
    _c("苏芙比买下摇滚苹果号后，船上由扎内塔担任什么职务？",
       "standkeeper（看塔人/管理员）",
       [["Zanetta", "standkeeper"], ["Rockin"]],
       type_="multi-hop", hop="multi", chapter="1.4"),
    _c("洞穴的囚徒篇里名为 Zero 的角色对应数字几？",
       "0（零，参照系原点）",
       [["Zero"]], chapter="1.4"),
]

# —— 1.1 雷米特杯失窃案 ——
HAND += [
    _c("雷米特杯失窃案里协助找回奖杯的侦探狗是谁？",
       "Pickles（皮克尔斯）",
       [["Pickles"]], chapter="其他"),
    _c("雷米特杯失窃案里留下名片的大盗是谁？",
       "Melania（梅兰妮，怪盗）",
       [["Melania"]], chapter="其他"),
    _c("拉米雷斯保安公司的老板是谁？",
       "Melania（梅兰妮）",
       [["Ramirez", "拉米雷斯", "雷米雷斯"], ["Melania"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("艾维森的英文名是什么？（雷米特杯失窃案）",
       "Iverson（艾维森）",
       [["Iverson"]], chapter="其他"),
    _c("威廉的英文名是什么？（雷米特杯失窃案）",
       "William（威廉）",
       [["William"]], chapter="其他"),
    _c("雷米特杯失窃案里出现的机器人保安英文叫什么？",
       "robot（机器人保安）",
       [["robot"]], chapter="其他"),
    _c("Melania 与 Pickles 同属哪一起案件？",
       "雷米特杯失窃案（1.1）",
       [["Melania"], ["Pickles"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("Acie 与 Iverson 同属哪一起案件？",
       "雷米特杯失窃案（1.1）",
       [["Acie"], ["Iverson"]],
       type_="multi-hop", hop="multi", chapter="其他"),
]

# —— 2.5 唐人街影话 ——
HAND += [
    _c("唐人街影话篇的故事发生在哪条街？",
       "唐人街（Chinatown）",
       [["Chinatown", "唐人街"]], chapter="其他"),
    _c("《神秘警探C07》系列的故事出自哪个篇章？",
       "唐人街影话（2.5）",
       [["C07", "神秘警探"]], chapter="其他"),
    _c("Noire 的中文译名是什么？",
       "菲林士多",
       [["菲林士多", "Noire"]], chapter="其他"),
    _c("梅林的英文名是什么？（唐人街影话篇）",
       "Merlin（梅林）",
       [["Merlin"]], chapter="其他"),
    _c("诺亚的英文名是什么？（唐人街影话篇）",
       "Noah（诺亚）",
       [["Noah"]], chapter="其他"),
    _c("斯科特的英文名是什么？（唐人街影话篇）",
       "Scott（斯科特）",
       [["Scott"]], chapter="其他"),
    _c("菲林士多与梅林同属哪个篇章？",
       "唐人街影话（2.5）",
       [["Noire", "菲林士多"], ["Merlin"]],
       type_="multi-hop", hop="multi", chapter="其他"),
]

# —— 1.8 再见，来亚什基 ——
HAND += [
    _c("再见，来亚什基篇里的村庄英文名是什么？",
       "Ryashki（来亚什基）",
       [["Ryashki"]], chapter="其他"),
    _c("来亚什基村里会神秘术的女老师是谁？",
       "维拉（Vila）",
       [["Vila", "维拉"], ["Ryashki"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("来亚什基的少年奥古斯特的英文名是什么？",
       "Avgust（奥古斯特）",
       [["Avgust"]], chapter="其他"),
    _c("叶夫根尼的英文名是什么？（再见，来亚什基篇）",
       "Yevgeny（叶夫根尼）",
       [["Yevgeny"]], chapter="其他"),
    _c("克努特的英文名是什么？（再见，来亚什基篇）",
       "Knut（克努特）",
       [["Knut"]], chapter="其他"),
    _c("来亚什基矿区出产的特殊矿物在英文里叫什么？",
       "Runium",
       [["Runium"], ["Ryashki"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("基克尔恩的英文名是什么？（再见，来亚什基篇）",
       "Kikirn（基克尔恩）",
       [["Kikirn"]], chapter="其他"),
    _c("温松的英文名是什么？（再见，来亚什基篇里的歌手）",
       "Winsong（温松）",
       [["Winsong"]], chapter="其他"),
    _c("有位少女教师用神秘术守护村庄，而这座村庄以矿业为生，这座村庄是哪里？",
       "来亚什基（Ryashki）",
       [["Ryashki"], ["Vila", "维拉"]],
       type_="reasoning", chapter="其他"),
    _c("温松与奥古斯特同为哪座村庄篇章里的人物？",
       "再见，来亚什基（1.8）",
       [["Winsong"], ["Avgust"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("基克尔恩与流明石同属哪座矿村的故事？",
       "来亚什基（Ryashki）",
       [["Kikirn"], ["Runium"]],
       type_="multi-hop", hop="multi", chapter="其他"),
]

# —— 2.2 忧郁的热带 ——
HAND += [
    _c("忧郁的热带篇里的女军官是谁？",
       "洛佩拉（Lopera）",
       [["Lopera", "洛佩拉"]], chapter="其他"),
    _c("卡森的英文名是什么？（忧郁的热带篇）",
       "Carson（卡森）",
       [["Carson"]], chapter="其他"),
    _c("邓肯的英文名是什么？（忧郁的热带篇）",
       "Duncan（邓肯）",
       [["Duncan"]], chapter="其他"),
    _c("莉莉娅的英文名是什么？（忧郁的热带篇）",
       "Lillia（莉莉娅）",
       [["Lillia"]], chapter="其他"),
    _c("佩拉的英文名是什么？（忧郁的热带篇）",
       "Pera（佩拉）",
       [["Pera"]], chapter="其他"),
    _c("使徒兄弟会的英文名是什么？（忧郁的热带篇）",
       "Apostles Brotherhood（使徒兄弟会）",
       [["Apostles Brotherhood", "Apostles"]], chapter="其他"),
    _c("卡森与邓肯同为哪个篇章里的人物？",
       "忧郁的热带（2.2）",
       [["Carson"], ["Duncan"]],
       type_="multi-hop", hop="multi", chapter="其他"),
]

# —— 2.1 77 号往事 ——
HAND += [
    _c("77 号往事中被误当作材料处置的农场女孩是谁？",
       "凯拉（Kayla）",
       [["Kayla", "凯拉"]], chapter="其他"),
    _c("77 号往事里淑女格蕾丝的英文名是什么？",
       "Grace（淑女格蕾丝）",
       [["Grace", "格蕾丝"], ["77"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("77 号往事里与格蕾丝对立的契约魅魔是谁？",
       "天使娜娜（Anjo Nala）",
       [["Anjo", "Nala", "娜娜", "Kimberly"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("金伯利女郎指的是谁？",
       "天使娜娜（Anjo Nala）",
       [["Kimberly", "Anjo", "Nala"]], chapter="其他"),
    _c("斯特凡的英文名是什么？（77 号往事）",
       "Stefan（斯特凡）",
       [["Stefan"]], chapter="其他"),
    _c("芭芭拉的英文名是什么？（77 号往事）",
       "Barbara（芭芭拉）",
       [["Barbara"]], chapter="其他"),
    _c("阿格斯的英文名是什么？（77 号往事）",
       "Argus（阿格斯）",
       [["Argus"]], chapter="其他"),
    _c("77 号往事发生在哪条公路沿线？",
       "77 号公路（Route 77）",
       [["77"]], chapter="其他"),
    _c("77 号往事发生在哪一年？",
       "1990 年",
       [["1990"]], type_="temporal", chapter="其他"),
    _c("被重塑之手追随者误认而遭处置的农场女孩死后，谁被迫长期扮演她在镇上生活？",
       "无名者（时以淑女格蕾丝身份行动）",
       [["Grace", "Stranger"], ["Kayla", "凯拉"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("凯拉被误认成了哪位重塑之手间谍？",
       "淑女格蕾丝（Grace，即无名者）",
       [["Kayla", "凯拉"], ["Grace", "格蕾丝"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("斯特凡与芭芭拉同为哪个篇章里的人物？",
       "77 号往事（2.1）",
       [["Stefan"], ["Barbara"]],
       type_="multi-hop", hop="multi", chapter="其他"),
]

# —— 2.4 地球上最后的夜晚 ——
HAND += [
    _c("自由海风号邮轮的英文名是什么？",
       "Free Breeze（自由海风号）",
       [["Free Breeze", "自由海风"]], chapter="其他"),
    _c("芭卡洛儿的故乡是哪座城市？",
       "克雷莫纳（Cremona，意大利小提琴之乡）",
       [["Cremona", "克雷莫纳"]], chapter="其他"),
    _c("在自由海风号上执行勿忘我的任务而精神崩溃的间谍是谁？",
       "无名者（Ms. Stranger，时为淑女格蕾丝）",
       [["Stranger", "无名者", "Grace"], ["Free Breeze"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("指派无名者登上自由海风号的重塑之手成员是谁？",
       "勿忘我（Forget-Me-Not）",
       [["Forget", "勿忘我"], ["Stranger", "Grace"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("努库泰澳岛的英文拼法是什么？",
       "Nukutai（努库泰澳）",
       [["Nukutai", "Nuku"]], chapter="其他"),
    _c("图图石子的英文名是什么？（地球上最后的夜晚篇）",
       "Fatutu（图图石子，Tutu）",
       [["Fatutu", "Tutu"]], chapter="其他"),
    _c("托阿的英文名是什么？（地球上最后的夜晚篇）",
       "Toa（托阿）",
       [["Toa"]], chapter="其他"),
    _c("塞洛尼的英文名是什么？（地球上最后的夜晚篇）",
       "Salone（塞洛尼）",
       [["Salone", "Selone"]], chapter="其他"),
    _c("梅莉的英文名是什么？（地球上最后的夜晚篇）",
       "Mellie（梅莉）",
       [["Mellie"]], chapter="其他"),
    _c("自由海风号的音乐总监芭卡洛儿来自哪座城市？",
       "克雷莫纳（Cremona）",
       [["Cremona", "克雷莫纳"], ["Barcarola", "芭卡洛儿"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("图图石子、托阿与塞洛尼共同生活在哪座岛上？",
       "努库泰澳（Nukutai）",
       [["Nukutai", "Nuku"], ["Toa", "Tutu"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("塞洛尼与卡穆塔同为哪座岛的岛民？",
       "努库泰澳（Nukutai）",
       [["Salone", "Selone"], ["Kamuta"]],
       type_="multi-hop", hop="multi", chapter="其他"),
]

# —— 1.5 复兴！乌卢鲁运动会 ——
HAND += [
    _c("乌卢鲁运动会圣火中的小精灵叫什么？",
       "Ulu（和平乌鲁）",
       [["Ulu", "和平乌鲁"]], chapter="其他"),
    _c("乌卢鲁运动会的主会场叫什么？",
       "乌卢鲁体育场（Uluru Stadium）",
       [["Uluru Stadium", "stadium"]], chapter="其他"),
    _c("乌卢鲁运动会的导演是谁？",
       "Ezra（以斯拉）",
       [["Ezra", "以斯拉"], ["Uluru", "乌卢鲁"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("参加乌卢鲁运动会的火焰系选手是谁？",
       "Spathodea（斯帕托迪亚）",
       [["Spathodea"]], chapter="其他"),
    _c("复兴！乌卢鲁运动会以哪座巨岩命名？",
       "乌卢鲁（Uluru，澳大利亚巨岩）",
       [["Uluru", "乌卢鲁"]], chapter="其他"),
    _c("马库阿的英文名是什么？（乌卢鲁运动会篇）",
       "Makua（马库阿）",
       [["Makua"]], chapter="其他"),
    _c("以火焰本能参赛并守护圣火的选手，与和平乌鲁多次同框，这位选手是谁？",
       "Spathodea（斯帕托迪亚）",
       [["Spathodea"], ["Ulu", "和平乌鲁"]],
       type_="reasoning", chapter="其他"),
    _c("以斯拉与斯帕托迪亚同为哪场运动会里的人物？",
       "复兴！乌卢鲁运动会（1.5）",
       [["Ezra"], ["Spathodea"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("一场运动会因位于澳洲腹地的巨岩而得名，这场运动会叫什么？",
       "乌卢鲁运动会",
       [["Uluru", "乌卢鲁"], ["games", "运动会"]],
       type_="reasoning", chapter="其他"),
]

# —— 2.3 圣火纪行：东区黎明 ——
HAND += [
    _c("伦敦雾霾事件里发明巨型净化机的先生是谁？",
       "Fogg（福格先生）",
       [["Fogg"], ["purifier", "净化"]],
       type_="reasoning", hop="multi", chapter="其他"),
    _c("福格先生发明的大型装置是什么？",
       "净化机（air purifier，伦敦雾霾净化装置）",
       [["purifier", "净化机", "purification"]], chapter="其他"),
    _c("卡罗琳·巴特利的英文名是什么？（圣火纪行篇）",
       "Caroline Bartley（卡罗琳·巴特利）",
       [["Caroline", "Bartley"]], chapter="其他"),
    _c("布里姆利的英文名是什么？（圣火纪行篇）",
       "Brimley（布里姆利）",
       [["Brimley"]], chapter="其他"),
    _c("圣火纪行篇里伦敦举办的选拔赛叫什么？",
       "伦敦资格赛",
       [["London", "伦敦"]], chapter="其他"),
    _c("福格先生与卡罗琳·巴特利同属哪个篇章？",
       "圣火纪行：东区黎明（2.3）",
       [["Fogg"], ["Caroline", "Bartley"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("一位伦敦绅士笃信机器能驱散整座城市的雾霾，他是谁？",
       "Fogg（福格先生）",
       [["Fogg"], ["London", "伦敦"]],
       type_="reasoning", chapter="其他"),
]

# —— 2.7 1987 宇宙组曲 ——
HAND += [
    _c("1987 宇宙组曲篇里远赴太空的旅人是谁？",
       "远旅（Voyager）",
       [["Voyager", "远旅"]], chapter="其他"),
    _c("波因特的英文名是什么？（1987 宇宙组曲篇）",
       "Pointer（波因特）",
       [["Pointer"]], chapter="其他"),
    _c("科兹洛夫的英文名是什么？（1987 宇宙组曲篇）",
       "Kozlov（科兹洛夫）",
       [["Kozlov", "科兹洛夫"]], chapter="其他"),
    _c("1987 宇宙组曲篇的发射任务与哪个矿区的资源有关？",
       "来亚什基矿区（Ryashki Mine）",
       [["Ryashki Mine", "Ryashki"], ["space", "太空"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("远旅与波因特同属哪个篇章？",
       "1987 宇宙组曲（2.7）",
       [["Voyager", "远旅"], ["Pointer"]],
       type_="multi-hop", hop="multi", chapter="其他"),
]

# —— 2.8 复乐园 ——
HAND += [
    _c("诺谛卡的英文名是什么？",
       "Nautica（诺谛卡）",
       [["Nautica"]], chapter="其他"),
    _c("复乐园篇的故事发生在哪块大陆？",
       "南极洲（Antarctica）",
       [["Antarctica", "南极"]], chapter="其他"),
    _c("乌尔里希也登场的南极篇章是哪一篇？",
       "复乐园（2.8）",
       [["Ulrich", "乌尔里希"], ["Antarctica", "南极"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("诺谛卡与南极洲同属哪个篇章？",
       "复乐园（2.8）",
       [["Nautica"], ["Antarctica", "南极"]],
       type_="multi-hop", hop="multi", chapter="其他"),
]

# —— 3.x 篇章（其他）——
HAND += [
    _c("阿黛尔的全名是什么？（迁流的盛宴篇）",
       "Adèle Tavernier（阿黛尔·塔维尼耶）",
       [["Tavernier", "Adèle", "Adele"]], chapter="其他"),
    _c("塞莉亚的英文名是什么？（迁流的盛宴篇）",
       "Celia（塞莉亚）",
       [["Celia"]], chapter="其他"),
    _c("费利西恩的英文名是什么？（迁流的盛宴篇）",
       "Felicien（费利西恩）",
       [["Felicien", "Felicienne", "Felician"]], chapter="其他"),
    _c("迁流的盛宴篇的故事发生在哪座城市？",
       "巴黎（Paris）",
       [["Paris", "巴黎"]], chapter="其他"),
    _c("塔维尼耶是迁流的盛宴篇里哪位角色的姓氏？",
       "阿黛尔（Adèle Tavernier）",
       [["Tavernier"], ["Adele", "Adèle"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("阿黛尔与塞莉亚同为哪座城市篇章里的人物？",
       "巴黎（Paris，迁流的盛宴）",
       [["Adele", "Adèle"], ["Celia"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("塞莉亚与费利西恩同属哪个篇章？",
       "迁流的盛宴（3.2）",
       [["Celia"], ["Felicien", "Felicienne", "Felician"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("绿松石蛇俱乐部篇的故事发生在哪个国家？",
       "墨西哥（Mexico）",
       [["Mexico", "墨西哥"]], chapter="其他"),
    _c("拉莫纳的英文名是什么？（绿松石蛇俱乐部篇）",
       "Ramona（拉莫纳）",
       [["Ramona", "拉莫纳"]], chapter="其他"),
    _c("绿松石蛇俱乐部篇里发生的命案中文叫什么？",
       "谋杀案",
       [["谋杀案", "murder"]], chapter="其他"),
    _c("蝴蝶小姐的英文名是什么？（绿松石蛇俱乐部篇）",
       "Senorita Butterfly（蝴蝶小姐）",
       [["Senorita", "Butterfly"]], chapter="其他"),
    _c("特蕾西塔的英文名是什么？（绿松石蛇俱乐部篇）",
       "Teresita（特蕾西塔）",
       [["Teresita"]], chapter="其他"),
    _c("穆里尔的英文名是什么？（绿松石蛇俱乐部篇）",
       "Muriel（穆里尔）",
       [["Muriel"]], chapter="其他"),
    _c("佩雷斯的英文名是什么？（绿松石蛇俱乐部篇）",
       "Perez（佩雷斯）",
       [["Perez"]], chapter="其他"),
    _c("拉莫纳与穆里尔同属哪个篇章？",
       "绿松石蛇俱乐部（3.5）",
       [["Ramona"], ["Muriel"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("克鲁托夫的英文名是什么？（远征记篇）",
       "Krutov（克鲁托夫）",
       [["Krutov"]], chapter="其他"),
    _c("伊万的英文名是什么？（远征记篇）",
       "Ivan（伊万）",
       [["Ivan"]], chapter="其他"),
    _c("远征记篇里的骑兵首领伊戈尔的英文名是什么？",
       "Igor（伊戈尔）",
       [["Igor", "伊戈尔"]], chapter="其他"),
    _c("谢尔盖的英文名是什么？（远征记篇）",
       "Sergei（谢尔盖）",
       [["Sergei", "谢尔盖"]], chapter="其他"),
    _c("克鲁托夫与伊万同为哪个篇章里草原军队的人物？",
       "远征记（3.3）",
       [["Krutov"], ["Ivan"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("长夜鸣笛篇的列车故事发生在哪条河流沿岸？",
       "多瑙河（Danube）",
       [["Danube", "多瑙河"]], chapter="其他"),
    _c("塞梅尔维斯的英文名是什么？（长夜鸣笛篇）",
       "Semmelweis（塞梅尔维斯）",
       [["Semmelweis"]], chapter="其他"),
    _c("野树莓的英文名是什么？（长夜鸣笛篇）",
       "Rubuska（野树莓）",
       [["Rubuska", "野树莓"]], chapter="其他"),
    _c("皮罗斯大叔的英文名是什么？（长夜鸣笛篇）",
       "Uncle Piros（皮罗斯大叔）",
       [["Piros"]], chapter="其他"),
    _c("长夜鸣笛篇里列车上的女售票员英文叫什么？",
       "conductress（女售票员）",
       [["conductress"]], chapter="其他"),
    _c("皮罗斯大叔与塞梅尔维斯同属哪个篇章？",
       "长夜鸣笛（3.1）",
       [["Piros"], ["Semmelweis"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("一列夜行列车上流传着吸血鬼的传闻，这条列车行驶在哪条河沿岸？",
       "多瑙河（Danube）",
       [["Danube", "多瑙河"], ["vampire"]],
       type_="reasoning", chapter="其他"),
    _c("入雅典记篇的故事发生在哪座城市？",
       "雅典（Athens）",
       [["Athens", "雅典"]], chapter="其他"),
    _c("入雅典记篇里雅典的统治者是谁？",
       "伯里克利（Pericles）",
       [["Pericles", "伯里克利"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("酒神节的英文名是什么？（入雅典记篇）",
       "Dionysia（酒神节）",
       [["Dionysia"]], chapter="其他"),
    _c("卡珊德拉的英文名是什么？（入雅典记篇）",
       "Cassandra（卡珊德拉）",
       [["Cassandra", "卡珊德拉"]], chapter="其他"),
    _c("雅典城邦的领袖主持了酒神节的庆典，他是谁？",
       "伯里克利（Pericles）",
       [["Pericles"], ["Dionysia"]],
       type_="reasoning", chapter="其他"),
    _c("伯里克利与酒神节同属哪座城市的故事？",
       "雅典（Athens，入雅典记）",
       [["Pericles"], ["Dionysia"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("卡珊德拉与得摩斯同属哪个篇章？",
       "入雅典记（联动）",
       [["Cassandra"], ["Deimos"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("翡冷翠之春篇中的城市指的是哪座意大利城市？",
       "佛罗伦萨（Firenze，翡冷翠）",
       [["Firenze", "翡冷翠"]], chapter="其他"),
    _c("乌切洛的英文名是什么？（翡冷翠之春篇）",
       "Uccello（乌切洛）",
       [["Uccello"]], chapter="其他"),
    _c("乌切洛活跃于哪座城市的篇章里？",
       "佛罗伦萨（Firenze，翡冷翠之春）",
       [["Uccello"], ["Firenze"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("不老春篇里村民们疯狂追求的东西是什么？",
       "长生（长生之法）",
       [["长生", "immortality"]], chapter="其他"),
    _c("不老春篇里的教派叫什么名字？",
       "梅花教",
       [["梅花教"]], chapter="其他"),
    _c("不老春篇里传说中的宝剑叫什么？",
       "长生剑",
       [["长生剑"]], chapter="其他"),
    _c("不老春篇里追求长生的教派叫什么？",
       "梅花教",
       [["梅花教"], ["长生"]],
       type_="reasoning", chapter="其他"),
    _c("梅花教与长生剑同属哪个篇章？",
       "不老春（3.4）",
       [["梅花教"], ["长生剑"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("朔日手记篇里酿得好酒的酒馆娘是谁？",
       "曲娘（Netto）",
       [["曲娘", "Netto"]], chapter="其他"),
    _c("朔日手记篇里九方之地举办的节日叫什么？",
       "杜硕节",
       [["杜硕节"]], chapter="其他"),
    _c("九方是朔日手记篇里的什么？",
       "九方（地点，朔日手记篇）",
       [["九方"]], chapter="其他"),
    _c("曲娘与杜硕节同属哪个篇章？",
       "朔日手记（1.6）",
       [["曲娘", "Netto"], ["杜硕节"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("聚合浪潮篇里的机器人集体组织叫什么？",
       "集体 2.0（Collective）",
       [["Collective", "集体2.0"]], chapter="其他"),
    _c("马克西姆的英文名是什么？（聚合浪潮篇）",
       "Maxim（马克西姆）",
       [["Maxim"]], chapter="其他"),
    _c("瓦尼亚的英文名是什么？（聚合浪潮篇）",
       "Vanya（瓦尼亚）",
       [["Vanya"]], chapter="其他"),
    _c("马克西姆与瓦尼亚同属哪个篇章？",
       "聚合浪潮（3.6）",
       [["Maxim"], ["Vanya"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("人们向何处去篇里拉普拉斯的重要装置是什么？",
       "玩具盒（toy box）",
       [["玩具盒", "toy box"]], chapter="其他"),
    _c("玩具盒与拉普拉斯同属哪个篇章？",
       "人们向何处去（3.6）",
       [["玩具盒", "toy box"], ["Laplace", "拉普拉斯"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("他者的悲哀篇里出现的学园缩写是什么？",
       "SPDM（初级防御学园）",
       [["SPDM", "初级防御学园"]], chapter="其他"),
    _c("SPDM 与初级防御学园出现在哪个篇章？",
       "他者的悲哀（3.7）",
       [["SPDM"], ["初级防御学园"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("重燃！流金之海篇里的海上神祇纳西索斯的英文名是什么？",
       "Narcissus（纳西索斯）",
       [["Narcissus"]], chapter="其他"),
    _c("赫多涅的英文名是什么？（重燃！流金之海篇）",
       "Hedone（赫多涅，Hedony）",
       [["Hedone", "Hedony"]], chapter="其他"),
    _c("重燃！流金之海篇里举办的水上竞技会英文叫什么？",
       "aquatic games（水上竞技会）",
       [["aquatic games", "aquatic"]], chapter="其他"),
    _c("纳西索斯与赫多涅同属哪个篇章？",
       "重燃！流金之海（3.9）",
       [["Narcissus"], ["Hedone", "Hedony"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("世纪末尺度篇里出现的时间异常现象英文叫什么？",
       "temporal anomaly（时间异常）",
       [["temporal anomaly", "anomaly"]], chapter="其他"),
]

# —— 世界观 / 无名者主线（其他）——
HAND += [
    _c("第一次暴雨发生于哪一天的午夜？",
       "1999 年 12 月 31 日",
       [["December", "31st", "31日"], ["1999"]],
       type_="temporal", chapter="其他"),
    _c("第一次暴雨发生于哪一年？",
       "1999 年",
       [["1999"]], type_="temporal", chapter="其他"),
    _c("1999 年 12 月 31 日那天发生了什么灾难？",
       "第一次暴雨",
       [["1999"], ["Storm", "暴雨", "storm"]],
       type_="temporal", hop="multi", chapter="其他"),
    _c("第一次暴雨是被哪个组织的仪式引发的？",
       "重塑之手（Manus Vindictae）",
       [["Manus", "重塑之手"], ["Storm", "暴雨"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("与圣洛夫基金会联手阻止重塑之手仪式的军备学院是哪家？",
       "芝诺军备学院（Zeno）",
       [["Zeno", "芝诺"], ["Foundation", "基金会"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("圣洛夫基金会的英文名与哪位条件反射理论家同名？",
       "巴甫洛夫（Pavlov）",
       [["Pavlov"]], type_="reasoning", chapter="其他"),
    _c("一家以条件反射理论家命名的基金会收容并管理神秘学家，它的英文名是什么？",
       "St. Pavlov Foundation（圣洛夫基金会）",
       [["Pavlov", "Foundation"]],
       type_="reasoning", chapter="其他"),
    _c("在暴雨中唯一能自由行动的司辰是谁？",
       "维尔汀（Vertin，Timekeeper）",
       [["Timekeeper", "司辰", "Vertin", "维尔汀"]], chapter="其他"),
    _c("维尔汀随身携带的、能庇护神秘学家的道具是什么？",
       "手提箱（suitcase，箱内别有洞天）",
       [["suitcase", "箱子", "手提箱"]], chapter="其他"),
    _c("圣洛夫基金会的副会长、无名者的养母是谁？",
       "康斯坦丁（Constantine）",
       [["Constantine", "康斯坦丁"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("重塑之手的首领是谁？",
       "阿尔卡纳（Arcana，别名受苦者）",
       [["Arcana", "阿尔卡纳"], ["Manus", "重塑之手"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("1929 年芝加哥瓦尔登湖酒吧的老板是谁？",
       "勿忘我（Forget-Me-Not）",
       [["Walden", "瓦尔登"], ["Forget", "勿忘我"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("芝加哥情人节大屠杀发生在哪一年？",
       "1929 年",
       [["1929"]], type_="temporal", chapter="其他"),
    _c("芝加哥情人节大屠杀发生在哪座城市？",
       "芝加哥（Chicago）",
       [["Chicago", "芝加哥"]], chapter="其他"),
    _c("芝加哥事件中瓦尔登湖酒吧的故事发生在哪一年？",
       "1929 年",
       [["Walden", "瓦尔登"], ["1929"]],
       type_="temporal", hop="multi", chapter="其他"),
    _c("一位神秘学家能免疫暴雨并带着手提箱穿越时代，她是谁？",
       "维尔汀（Vertin）",
       [["Vertin", "Timekeeper", "suitcase"]],
       type_="reasoning", chapter="其他"),
    _c("有人把两位好友的消失归咎于一场暴雨，这位幸存的司辰是谁？",
       "维尔汀（Vertin）",
       [["Vertin", "Timekeeper", "维尔汀"], ["Storm", "暴雨"]],
       type_="reasoning", chapter="其他"),
    _c("有人以“浸没于纯白中的执棋者”形容一位总是面带微笑的副会长，她是谁？",
       "康斯坦丁（Constantine）",
       [["Constantine", "康斯坦丁"]], type_="reasoning", chapter="其他"),
    _c("一位基金会副会长常以棋局比喻事件，她也是无名者的养母，她是谁？",
       "康斯坦丁（Constantine）",
       [["Constantine", "康斯坦丁"]], type_="reasoning", chapter="其他"),
    _c("一个组织的首领别名“受苦者”，是芝加哥与维也纳事件的罪魁祸首，她是谁？",
       "阿尔卡纳（Arcana）",
       [["Arcana", "阿尔卡纳"], ["Manus", "重塑之手"]],
       type_="reasoning", chapter="其他"),
    _c("一个组织试图回溯至“秩序正确”的时代并人为加速暴雨的到来，它是谁？",
       "重塑之手（Manus Vindictae）",
       [["Manus", "重塑之手"], ["Storm", "暴雨"]],
       type_="reasoning", chapter="其他"),
    _c("由鸽子意象命名、与基金会收容事务相关的场所有个绰号，它叫什么？",
       "鸽子屋（The Pax House）",
       [["Pax House", "鸽子屋"]], type_="reasoning", chapter="其他"),
    _c("无名者的神秘术能把记忆转换成什么？",
       "飞蛾（鳞翅目）",
       [["moth", "蛾"]], chapter="其他"),
    _c("无名者幼年被植入的、能生成人格与记忆的装置叫什么？",
       "发条装置（clockwork）",
       [["clockwork", "发条"]], chapter="其他"),
    _c("康斯坦丁给无名者的第一个名字是什么？",
       "普帕（Pupa，意为蛹）",
       [["Pupa", "普帕"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("无名者在基金会内务档案中的机构代号是什么？",
       "飞蛾（Moth）",
       [["moth", "Moth"]], chapter="其他"),
    _c("一位特工能把记忆化作飞蛾循光传递情报，她是谁？",
       "无名者（Ms. Stranger）",
       [["moth", "Stranger", "无名者", "Grace"]],
       type_="reasoning", chapter="其他"),
    _c("在康复中心为无名者做人工梦游诊察的医生是谁？",
       "小梅斯梅尔（Mesmer Jr.）",
       [["Mesmer"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("一位怀疑神秘学家终将被淘汰的精神科医生坚持在康复中心工作，她是谁？",
       "小梅斯梅尔（Mesmer Jr.）",
       [["Mesmer"]], type_="reasoning", chapter="其他"),
    _c("一位精神科医生的同学包括维尔汀与玛蒂尔达，她是谁？",
       "小梅斯梅尔（Mesmer Jr.）",
       [["Mesmer"], ["Matilda", "玛蒂尔达"]],
       type_="reasoning", chapter="其他"),
    _c("第一次大决战后康斯坦丁派去监视重塑之手的间谍是谁？",
       "淑女格蕾丝（Grace，即无名者）",
       [["Grace", "格蕾丝"], ["Constantine", "康斯坦丁"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("一位女士既是基金会间谍又以“淑女”自称，她的化名是什么？",
       "淑女格蕾丝（Grace）",
       [["Grace", "格蕾丝"], ["Foundation", "基金会"]],
       type_="reasoning", chapter="其他"),
    _c("被阿尔卡纳称作“我的无名者”、以蛹为喻的角色是谁？",
       "无名者（Ms. Stranger）",
       [["Stranger", "无名者", "Grace"]], type_="reasoning", chapter="其他"),
    _c("基金会的首席助手、维尔汀的第一防线学校同窗是谁？",
       "十四行诗（Sonnet）",
       [["Sonnet"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("十四行诗的英文名是什么？",
       "Sonnet（十四行诗）",
       [["Sonnet"]], chapter="其他"),
    _c("玛蒂尔达的英文名是什么？",
       "Matilda Bouanich（玛蒂尔达）",
       [["Matilda", "Bouanich", "Boaniche"]], chapter="其他"),
    _c("星锑的英文名是什么？",
       "Regulus（星锑）",
       [["Regulus", "星锑"]], chapter="其他"),
    _c("苏芙比的英文名是什么？",
       "Sotheby（苏芙比）",
       [["Sotheby", "苏芙比"]], chapter="其他"),
    _c("牙仙的英文名是什么？",
       "Tooth Fairy（牙仙）",
       [["Tooth Fairy", "牙仙"]], chapter="其他"),
    _c("神秘学家的英文叫什么？",
       "Arcanist（神秘学家）",
       [["Arcanist", "arcanist"]], chapter="其他"),
    _c("重塑之手的英文叫什么？",
       "Manus Vindictae（重塑之手）",
       [["Manus Vindictae", "Manus"]], chapter="其他"),
    _c("圣洛夫基金会的英文全称是什么？",
       "St. Pavlov Foundation（圣洛夫基金会）",
       [["Pavlov", "St. Pavlov", "St Pavlov"]], chapter="其他"),
    _c("鸽子屋的英文名是什么？",
       "The Pax House（鸽子屋）",
       [["Pax House", "鸽子屋"]], chapter="其他"),
    _c("拉普拉斯的英文叫什么？",
       "Laplace（拉普拉斯科算中心，LSCC）",
       [["Laplace", "LSCC"]], chapter="其他"),
    _c("芝诺的英文叫什么？",
       "Zeno（芝诺军备学院）",
       [["Zeno", "芝诺"]], chapter="其他"),
    _c("暴雨的英文叫什么？",
       "The Storm（暴雨）",
       [["Storm", "storm"]], chapter="其他"),
    _c("司辰的英文叫什么？",
       "Timekeeper（司辰）",
       [["Timekeeper"]], chapter="其他"),
    _c("一位海盗歌手的座船由苏芙比出资购买，这位歌手是谁？",
       "星锑（Regulus）",
       [["Regulus", "星锑"], ["Sotheby", "苏芙比"]],
       type_="reasoning", chapter="其他"),
    _c("一位来自小提琴之乡的女士担任邮轮音乐总监，她是谁？",
       "芭卡洛儿（Barcarola Stradivari）",
       [["Barcarola", "芭卡洛儿"], ["Cremona", "克雷莫纳"]],
       type_="reasoning", chapter="其他"),
    _c("一位少女的同伴以数字命名，她自己也是如此，她叫什么？",
       "37",
       [["37"], ["Six"]], type_="reasoning", chapter="其他"),
    _c("一位少女随维尔汀离开海岛以躲避暴雨回溯，她是谁？",
       "37",
       [["37"], ["Apeiron", "阿派朗"]],
       type_="reasoning", chapter="其他"),
    _c("一位随维尔汀行动的女演员最终开枪杀死了一名重塑之手成员，她是谁？",
       "伊索尔德（Isolde）",
       [["Isolde", "伊索尔德"], ["Heinrich", "海因里希"]],
       type_="reasoning", chapter="其他"),
    _c("维尔汀在第一防线学校时是多少岁策划学生出逃的？",
       "12 岁",
       [["twelve", "12岁", "12 years"]],
       type_="temporal", chapter="其他"),
    _c("1966 年的伦敦与哪位海盗歌手的故事有关？",
       "星锑（Regulus）",
       [["1966"], ["Regulus", "星锑"]],
       type_="temporal", hop="multi", chapter="其他"),
    _c("1966 年维尔汀首次登场于哪座城市？",
       "伦敦（London）",
       [["1966"], ["London", "伦敦"]],
       type_="temporal", hop="multi", chapter="其他"),
]

# —— 1.7 补充 / 1.9 补充 / 1971 补充（凑齐每章配额）——
HAND += [
    _c("血痛概念出现在哪个维也纳篇章里？",
       "今夜星光灿烂（1.7）",
       [["bloody pain"], ["Vienna", "维也纳"]], chapter="1.7"),
    _c("格蕾塔与多里斯同属哪个篇章？",
       "今夜星光灿烂（1.7 维也纳篇）",
       [["Greta", "Hofmann"], ["Doris"]],
       type_="multi-hop", hop="multi", chapter="1.7"),
    _c("特奥菲尔与马库斯一起调查的事件发生在哪座城市？",
       "维也纳（Vienna）",
       [["Teofil"], ["Marcus"], ["Vienna", "维也纳"]],
       type_="multi-hop", hop="multi", chapter="1.7"),
    _c("孤独之歌篇里的研究卷轴与绳结等道具出现在哪座岛上？",
       "阿派朗岛（Apeiron）",
       [["scroll", "卷轴"], ["Apeiron", "阿派朗"]],
       type_="multi-hop", hop="multi", chapter="1.9"),
    _c("孤独之歌篇里零号概念的讲解围绕数字几展开？",
       "0（零，参照系原点）",
       [["Zero"], ["Apeiron", "阿派朗"]], chapter="1.9"),
    _c("苏菲亚在阿尔卡纳之后接管了哪个组织？",
       "重塑之手（Manus Vindictae）",
       [["Sophia", "苏菲亚"], ["Manus", "重塑之手"]],
       type_="multi-hop", hop="multi", chapter="1.9"),
    _c("冷周六与巨怪传说同属哪个篇章？",
       "绿湖噩梦（1971）",
       [["Hissabeth"], ["troll", "巨怪"]],
       type_="multi-hop", hop="multi", chapter="1971"),
    _c("Horropedia 与 Jessica 同属哪个营地的故事？",
       "绿湖营地（Green Lake camp，1971）",
       [["Horropedia"], ["Jessica"]],
       type_="multi-hop", hop="multi", chapter="1971"),
    _c("绿湖噩梦篇里的灯塔传说与哪个营地相关？",
       "绿湖营地（Green Lake camp）",
       [["灯塔", "lighthouse"], ["camp", "Green Lake"]], chapter="1971"),
    _c("洞穴的囚徒篇里的恶魔荆棘是什么？",
       "恶魔荆棘（物品/武器，洞穴的囚徒篇）",
       [["恶魔荆棘", "荆棘"]], chapter="1.4"),
    _c("洞穴的囚徒篇里牙仙也登船照看乘客，她的英文名是什么？",
       "Tooth Fairy（牙仙）",
       [["Tooth Fairy", "牙仙"], ["Sotheby", "Regulus"]], chapter="1.4"),
    _c("洞穴的囚徒篇里的努玛是什么？",
       "Numa（努玛，洞穴的囚徒篇物品）",
       [["Numa"]], chapter="1.4"),
    _c("洞穴的囚徒篇里的亚瑟的英文名是什么？",
       "Arthur（亚瑟）",
       [["Arthur"]], chapter="1.4"),
    # —— 1.4 补充池 ——
    _c("洞穴的囚徒篇里的洞穴隐喻出自哪位哲学家的理论？",
       "柏拉图（Plato，洞穴寓言）",
       [["Plato", "柏拉图"]], chapter="1.4"),
    _c("随维尔汀乘船出行、擅长专注倾听的基金会助手是谁？",
       "十四行诗（Sonnet）",
       [["Sonnet"]], chapter="1.4"),
    _c("洞穴的囚徒篇里随行的火焰系角色是谁？",
       "Spathodea（斯帕托迪亚）",
       [["Spathodea"]], chapter="1.4"),
    _c("洞穴的囚徒篇里的 J 先生的英文名是什么？",
       "Jay（J，乔·布朗）",
       [["Jay", "乔·布朗"]], chapter="1.4"),
    _c("洞穴的囚徒篇里自称经验丰富的猎人的角色是谁？",
       "Shamane（沙曼）",
       [["Shamane", "hunter"]], chapter="1.4"),
    _c("洞穴的囚徒篇里呼啸而来的巨兽叫什么？",
       "Braxxus（巨兽，洞穴的囚徒篇）",
       [["Braxxus"]], chapter="1.4"),
    _c("洞穴的囚徒篇里的摇滚苹果号是同名的第几代船？",
       "第二代（the second of its name）",
       [["second", "Rockin"]], chapter="1.4"),
    _c("洞穴的囚徒篇里陪维尔汀整理档案的义妹是谁？",
       "保利娜（Paulina）",
       [["Paulina"], ["Sotheby", "Regulus"]],
       type_="multi-hop", hop="multi", chapter="1.4"),
    _c("在洞穴的囚徒篇里负责照看乘客健康的牙医英文名叫什么？",
       "Tooth Fairy（牙仙）",
       [["Tooth Fairy", "牙仙"], ["ship", "Rockin"]], chapter="1.4"),
    _c("洞穴的囚徒篇中与管理船只日常的 standkeeper 对话的是谁？",
       "Zanetta 与维尔汀一行（洞穴的囚徒篇）",
       [["Zanetta"], ["Vertin", "Timekeeper"]],
       type_="multi-hop", hop="multi", chapter="1.4"),
]

# 追加 1.4（原列表已在上面闭合，这里用独立块继续添加）
HAND += [
    _c("自称经验丰富的猎人的 Shamane 活跃于哪个篇章？",
       "洞穴的囚徒（1.4）",
       [["Shamane"], ["Sotheby", "Regulus", "Rockin"]],
       type_="multi-hop", hop="multi", chapter="1.4"),
]

# —— 1971 补充池 ——
HAND += [
    _c("绿湖噩梦篇里的巨怪英文叫什么？",
       "troll（巨怪）",
       [["troll"]], chapter="1971"),
    _c("绿湖营地发生的案件类型是什么？",
       "失踪案（绿湖噩梦）",
       [["失踪", "missing"]], chapter="1971"),
    _c("绿湖噩梦篇里的巨怪居住在什么地方？",
       "暗林（森林深处）",
       [["暗林", "woods", "forest"]], chapter="1971"),
    _c("绿湖营地的孩子们不敢进入的是哪里？",
       "森林（暗林，巨怪出没之地）",
       [["woods", "forest", "森林", "暗林"]],
       type_="reasoning", chapter="1971"),
    _c("绿湖噩梦篇里出现的青年组织叫什么？",
       "青年军",
       [["青年军"]], chapter="1971"),
    _c("牙仙与 Jessica 同属哪个营地的故事？",
       "绿湖营地（Green Lake camp，1971）",
       [["Tooth Fairy", "牙仙"], ["Jessica"]],
       type_="multi-hop", hop="multi", chapter="1971"),
    _c("绿湖噩梦篇里孩子们口口相传的怪物住在森林还是湖底？",
       "森林（暗林，troll 出没）",
       [["troll", "巨怪"], ["woods", "forest", "暗林"]],
       type_="reasoning", chapter="1971"),
    _c("在 1971 年的绿湖营地，负责孩子们医疗健康的医生英文名叫什么？",
       "Tooth Fairy（牙仙）",
       [["Tooth Fairy", "牙仙"], ["Green Lake", "camp"]], chapter="1971"),
    _c("绿湖噩梦篇里巨怪与青年军同框出现的事件发生在哪一年？",
       "1971 年（绿湖噩梦）",
       [["troll", "巨怪"], ["青年军"]],
       type_="multi-hop", hop="multi", chapter="1971"),
    _c("绿湖噩梦篇里的 Jessica 与 Freddy 同为哪个营地的孩子？",
       "绿湖营地（Green Lake camp）",
       [["Jessica"], ["Freddy"], ["camp", "Green Lake"]],
       type_="multi-hop", hop="multi", chapter="1971"),
]

# —— 多跳单组补充（hop=multi，链式关系写进题干；答案词单组）——
HAND += [
    _c("苏菲亚从阿尔卡纳手中接管的组织叫什么？",
       "重塑之手（Manus Vindictae）",
       [["Manus", "重塑之手"]], type_="multi-hop", hop="multi", chapter="其他"),
    _c("苏菲亚与阿尼姆斯在南极事件中复活了谁？",
       "阿尔卡纳（Arcana）",
       [["Arcana", "阿尔卡纳"]], type_="multi-hop", hop="multi", chapter="其他"),
    _c("康斯坦丁的养女最终以什么身份加入司辰小队？",
       "无名者（Ms. Stranger）",
       [["Stranger", "无名者"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("破坏无名者发条装置的重塑之手首领是谁？",
       "阿尔卡纳（Arcana）",
       [["Arcana", "阿尔卡纳"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("保利娜的义兄、人称 J 的男人叫什么名字？",
       "J（乔·布朗，Jay）",
       [["Jay", "乔·布朗"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("乔·布朗的义妹、原基金会调查员是谁？",
       "保利娜（Paulina）",
       [["Paulina", "保利娜"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("芝加哥事件中被阿尔卡纳折磨的少女是谁？",
       "斯奈德（Snyder）",
       [["Snyder", "斯奈德"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("救走斯奈德姐姐的行动发生在哪座城市？",
       "芝加哥（Chicago）",
       [["Chicago", "芝加哥"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("可燃点体内的和平乌鲁与哪场运动会的圣火相关？",
       "乌卢鲁运动会",
       [["Uluru", "乌卢鲁"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("以斯拉导演的运动会里，圣火的本体是谁？",
       "Ulu（和平乌鲁）",
       [["Ulu", "和平乌鲁"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("施瓦茨医生的骗局最终被哪位维也纳医生揭穿？",
       "卡卡尼亚（Kakania）",
       [["Kakania", "卡卡尼亚"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("海因里希效忠的重塑之手首领是谁？",
       "阿尔卡纳（Arcana）",
       [["Arcana", "阿尔卡纳"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("拉莫纳的俱乐部坐落在哪个国家？",
       "墨西哥（Mexico）",
       [["Mexico", "墨西哥"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("曲娘的酒馆位于朔日手记篇的哪个地点？",
       "九方",
       [["九方"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("杜硕节在朔日手记篇的哪个地点举办？",
       "九方",
       [["九方"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("维拉守护的来亚什基村庄出产的特殊矿物叫什么？",
       "Runium",
       [["Runium"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("温松的歌声回荡在哪座矿业村庄？",
       "来亚什基（Ryashki）",
       [["Ryashki"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("福格先生的净化机是为了哪座城市的雾霾而造？",
       "伦敦（London）",
       [["London", "伦敦"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("诺谛卡出现的大陆是哪块？",
       "南极洲（Antarctica）",
       [["Antarctica", "南极"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("本名克拉拉·温格勒的医生在维也纳以什么名字为人所知？",
       "卡卡尼亚（Kakania）",
       [["Kakania", "卡卡尼亚"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("苏芙比买下摇滚苹果号是为了航行到哪座岛？",
       "阿派朗岛（Apeiron）",
       [["Apeiron", "阿派朗"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("37 随维尔汀离开海岛是为了躲避什么灾难的回溯？",
       "暴雨（The Storm）",
       [["Storm", "暴雨"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("在阿派朗岛被真空弹轰炸灰飞烟灭的重塑之手首领是谁？",
       "阿尔卡纳（Arcana）",
       [["Arcana", "阿尔卡纳"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("斯奈德的姐姐被囚禁在瓦尔登湖酒吧的哪里？",
       "酒吧密室",
       [["Snyder", "斯奈德"], ["Walden", "瓦尔登"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("被勿忘我要求戴上面具以测试忠诚的角色是谁？",
       "无名者（淑女格蕾丝）",
       [["Grace", "Stranger", "无名者"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("慧姑追求的长生之法与不老春篇的哪个教派有关？",
       "梅花教",
       [["梅花教"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("在自由海风号上经历试炼的乘客们乘坐的邮轮英文名叫什么？",
       "Free Breeze（自由海风号）",
       [["Free Breeze"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("图图石子生活的努库泰澳岛位于哪篇故事里？",
       "地球上最后的夜晚（2.4）",
       [["Fatutu", "Tutu"], ["Nukutai", "Nuku"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("阿尔卡纳盯上的非对称核素 R 可以让人免疫什么灾难？",
       "暴雨（The Storm）",
       [["Storm", "暴雨"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("维尔汀用哪个道具庇护了逃过暴雨的神秘学家们？",
       "手提箱（suitcase）",
       [["suitcase", "箱子"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("在拉普拉斯科算中心康复中心就职的精神科医生是谁？",
       "小梅斯梅尔（Mesmer Jr.）",
       [["Mesmer"], ["Laplace", "拉普拉斯"]],
       type_="multi-hop", hop="multi", chapter="其他"),
]

# —— 短题干补充（text_len=short）——
HAND += [
    _c("J 的英文名是什么？", "Jay（J，乔·布朗）",
       [["Jay", "乔·布朗"]], chapter="其他"),
    _c("伊戈尔是谁？", "Igor（伊戈尔，远征记骑兵首领）",
       [["Igor", "伊戈尔"]], chapter="其他"),
    _c("多瑙河的英文叫什么？", "Danube（多瑙河）",
       [["Danube", "多瑙河"]], chapter="其他"),
    _c("雅典的英文叫什么？", "Athens（雅典）",
       [["Athens", "雅典"]], chapter="其他"),
    _c("LSCC 是什么机构？", "Laplace（拉普拉斯科算中心）",
       [["Laplace", "LSCC"]], chapter="其他"),
    _c("乌尔里希是谁？", "Ulrich（乌尔里希，阿派朗岛研究者）",
       [["Ulrich", "乌尔里希"]], chapter="1.9"),
    _c("露西是谁？", "Lucy（露西）",
       [["Lucy", "露西"]], chapter="1.9"),
    _c("Charon 是谁？", "Charon（卡戎，摆渡人）",
       [["Charon", "卡戎"]], chapter="其他"),
    _c("Enigma 是谁？", "Enigma（哑谜）",
       [["Enigma", "哑谜"]], chapter="其他"),
    _c("芝加哥的英文叫什么？", "Chicago（芝加哥）",
       [["Chicago", "芝加哥"]], chapter="其他"),
    _c("雅致的多瑙河篇章名是什么？", "长夜鸣笛（3.1）",
       [["Danube"], ["vampire"]], chapter="其他"),
]

# —— 长题干补充（text_len=long）——
HAND += [
    _c("在《重返未来：1999》第一章的芝加哥事件里，经营瓦尔登湖地下酒吧的重塑之手成员是谁？",
       "勿忘我（Forget-Me-Not）",
       [["Forget", "勿忘我"]], type_="multi-hop", hop="multi", chapter="其他"),
    _c("在 1990 年德克萨斯 77 号公路的往事里，被重塑之手追随者误认成格蕾丝的农场女孩是谁？",
       "凯拉（Kayla）",
       [["Kayla", "凯拉"]], type_="multi-hop", hop="multi", chapter="其他"),
    _c("在绿湖噩梦篇的营地传说里，孩子们深信森林暗处潜伏着哪一种怪物？",
       "巨怪（troll）",
       [["troll", "巨怪"]], type_="multi-hop", hop="multi", chapter="1971"),
    _c("在孤独之歌篇的阿派朗岛上，与 37 同以数字为名、被称作“六”的少女叫什么？",
       "Six（六）",
       [["Six"]], type_="multi-hop", hop="multi", chapter="1.9"),
    _c("在今夜星光灿烂篇的维也纳舞台上红极一时、最终枪杀海因里希的女演员是谁？",
       "伊索尔德（Isolde）",
       [["Isolde", "伊索尔德"]],
       type_="multi-hop", hop="multi", chapter="1.7"),
    _c("在洞穴的囚徒篇的航行里，出资买下摇滚苹果号、随身携带药箱的贵族小姐是谁？",
       "苏芙比（Sotheby）",
       [["Sotheby", "苏芙比"]],
       type_="multi-hop", hop="multi", chapter="1.4"),
    _c("在雷米特杯失窃案里协助警方寻回失窃奖杯、因此声名大噪的侦探狗叫什么名字？",
       "Pickles（皮克尔斯）",
       [["Pickles"]], type_="multi-hop", hop="multi", chapter="其他"),
    _c("在迁流的盛宴篇的巴黎社交季里，出身塔维尼耶家族的年轻女士是谁？",
       "阿黛尔（Adèle Tavernier）",
       [["Tavernier", "Adele", "Adèle"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("在绿松石蛇俱乐部的墨西哥故事里，与画家圈子来往密切的女主角是谁？",
       "拉莫纳（Ramona）",
       [["Ramona", "拉莫纳"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("在入雅典记的雅典城邦故事里，主持酒神节、执掌城邦的领袖人物是谁？",
       "伯里克利（Pericles）",
       [["Pericles", "伯里克利"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("在长夜鸣笛篇的多瑙河夜行列车上，与吸血鬼传闻纠缠在一起的女学者是谁？",
       "塞梅尔维斯（Semmelweis）",
       [["Semmelweis"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("在 1987 宇宙组曲篇的太空任务里，跨越星海、远赴外层空间的旅人是谁？",
       "远旅（Voyager）",
       [["Voyager", "远旅"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("在再见来亚什基篇的矿业村庄里，教孩子们唱歌、想去看海的少年是谁？",
       "Avgust（奥古斯特）",
       [["Avgust"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("在忧郁的热带篇的圣保罗贫民窟故事里，身居军职、行事果决的女军官是谁？",
       "洛佩拉（Lopera）",
       [["Lopera", "洛佩拉"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("在圣火纪行东区黎明的伦敦雾霾里，坚信自己的巨型机器能净化全城的绅士是谁？",
       "Fogg（福格先生）",
       [["Fogg"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("在复兴乌卢鲁运动会篇的赛场上，操控火焰参赛、守护和平乌鲁圣火的选手是谁？",
       "Spathodea（斯帕托迪亚）",
       [["Spathodea"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("在地球上最后的夜晚篇的南太平洋航线上，奉命登船执行任务、代号淑女格蕾丝的间谍是谁？",
       "无名者（Ms. Stranger）",
       [["Stranger", "Grace", "无名者"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("在疯癫与文明篇的科马拉全景监狱故事里，与虚构集并肩行动的非因果性研究者是谁？",
       "阿莱夫（Aleph）",
       [["Aleph", "阿莱夫"], ["Recoleta", "虚构集"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("在朔日手记篇的大唐九方之地，于杜硕节期间酿出令人称奇的好酒的娘子是谁？",
       "曲娘（Netto）",
       [["曲娘", "Netto"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("在唐人街影话篇的香港取景故事里，执导《神秘警探C07》三部曲的导演是谁？",
       "菲林士多（Noire）",
       [["Noire", "菲林士多"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("在无路可返的个人剧情里，于康复中心为无名者进行人工梦游诊察的医生是谁？",
       "小梅斯梅尔（Mesmer Jr.）",
       [["Mesmer"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("在第一次暴雨降临的 1999 年 12 月 31 日夜里，试图穿越时空回到空白时代的组织是谁？",
       "重塑之手（Manus Vindictae）",
       [["Manus", "重塑之手"], ["1999"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("在阿派朗岛事件里临终托付、把重塑之手领袖之位交给苏菲亚的人是谁？",
       "阿尔卡纳（Arcana）",
       [["Arcana", "阿尔卡纳"], ["Sophia", "苏菲亚"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("在绿湖噩梦篇的夏令营里，一边讲恐怖片桥段一边协助调查失踪案的男孩是谁？",
       "Horropedia（恐怖片迷）",
       [["Horropedia"]],
       type_="multi-hop", hop="multi", chapter="1971"),
    _c("在今夜星光灿烂篇的维也纳社交场里，本姓温格勒、以精神分析见长的年轻医生是谁？",
       "卡卡尼亚（Kakania）",
       [["Kakania", "卡卡尼亚"]],
       type_="multi-hop", hop="multi", chapter="1.7"),
    _c("在洞穴的囚徒篇的开场里，向维尔汀递交钥匙、请她整理档案的管家是谁？",
       "Zanetta（扎内塔）",
       [["Zanetta"]],
       type_="multi-hop", hop="multi", chapter="1.4"),
    _c("在孤独之歌篇的结尾，被维尔汀拦下并带离海岛、躲过暴雨回溯的数字少女是谁？",
       "37",
       [["37"], ["Apeiron", "阿派朗"]],
       type_="multi-hop", hop="multi", chapter="1.9"),
    _c("在雷米特杯失窃案的调查过程中，与侦探狗并肩找出大盗梅兰妮线索的机器人叫什么？",
       "robot（机器人保安）",
       [["robot"], ["Melania"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("在聚合浪潮篇的苏联背景故事里，与集体 2.0 的机器人群体打交道的研究者是谁？",
       "Maxim（马克西姆）",
       [["Maxim"]],
       type_="multi-hop", hop="multi", chapter="其他"),
    _c("在远征记篇的草原战争故事里，统率骑兵部队、与伊戈尔共事的将领是谁？",
       "Krutov（克鲁托夫）",
       [["Krutov"], ["Igor", "伊戈尔"]],
       type_="multi-hop", hop="multi", chapter="其他"),
]


# ── 2b. hop 重标定 ─────────────────────────────────────────────────────────
# 以下题目第二组证据只是题干场景限定词，事实本身单跳即可回答，
# 显式标为 hop=single（2 组证据 → depth/difficulty=medium）。
RETAG_SINGLE_QS = {
    "今夜星光灿烂篇中红极一时的维也纳女演员是谁？",
    "以电击治疗骗财、与卡卡尼亚对峙的医生是谁？",
    "血痛概念出现在哪个维也纳篇章里？",
    "孤独之歌这个篇章名，与哪位独自留守海岛、钻研数学的数字少女有关？",
    "孤独之歌篇里的研究卷轴与绳结等道具出现在哪座岛上？",
    "孤独之歌篇里零号概念的讲解围绕数字几展开？",
    "绿湖营地的传说中，森林里出没的怪物是什么？",
    "巨怪传说与失踪案发生在哪一年的绿湖？",
    "绿湖噩梦篇的孩子们在森林里遭遇了什么怪物？",
    "在 1971 年的绿湖营地，负责孩子们医疗健康的医生英文名叫什么？",
    "绿湖噩梦篇里的灯塔传说与哪个营地相关？",
    "伦敦十字街的雾中女巫是谁？",
    "在洞穴的囚徒篇里负责照看乘客健康的牙医英文名叫什么？",
    "洞穴的囚徒篇里牙仙也登船照看乘客，她的英文名是什么？",
    "洞穴的囚徒篇里保利娜也随行登场，她的英文名是什么？",
    "洞穴的囚徒篇中与管理船只日常的 standkeeper 对话的是谁？",
    "以火焰本能参赛并守护圣火的选手，与和平乌鲁多次同框，这位选手是谁？",
    "不老春篇里追求长生的教派叫什么？",
    "一列夜行列车上流传着吸血鬼的传闻，这条列车行驶在哪条河沿岸？",
    "雅典城邦的领袖主持了酒神节的庆典，他是谁？",
    "一场运动会因位于澳洲腹地的巨岩而得名，这场运动会叫什么？",
    "一位少女的同伴以数字命名，她自己也是如此，她叫什么？",
    "有位少女教师用神秘术守护村庄，而这座村庄以矿业为生，这座村庄是哪里？",
    "一位伦敦绅士笃信机器能驱散整座城市的雾霾，他是谁？",
    "拉米雷斯保安公司的老板是谁？",
    "来亚什基矿区出产的特殊矿物在英文里叫什么？",
    "绿湖噩梦篇里孩子们口口相传的怪物住在森林还是湖底？",
    "苏芙比买下摇滚苹果号后，船上由扎内塔担任什么职务？",
}

for _cand in SEEDS + HAND:
    if _cand["q"] in RETAG_SINGLE_QS:
        _cand["dims"]["hop"] = "single"

# —— 1.7 / 1.9 补充池（扩大章节余量 + medium-single）——
HAND += [
    _c("海因里希的英文名是什么？", "Heinrich（海因里希）",
       [["Heinrich", "海因里希"]], chapter="1.7"),
    _c("伊索尔德的英文名是什么？", "Isolde（伊索尔德）",
       [["Isolde", "伊索尔德"]], chapter="1.7"),
    _c("维也纳的英文叫什么？", "Vienna（维也纳）",
       [["Vienna", "维也纳"]], chapter="1.7"),
    _c("施瓦茨的英文名是什么？", "Schwartz（施瓦茨）",
       [["Schwartz", "施瓦茨"]], chapter="1.7"),
    _c("海因里希效忠的重塑之手在英文里叫什么？", "Manus Vindictae（重塑之手）",
       [["Manus", "重塑之手"], ["Heinrich", "海因里希"]],
       hop="single", chapter="1.7"),
    _c("索菲亚的英文名是什么？", "Sophia（苏菲亚）",
       [["Sophia", "苏菲亚"]], chapter="1.9"),
    _c("苏菲亚与 37 同属哪个篇章？", "孤独之歌（1.9，阿派朗岛）",
       [["Sophia", "苏菲亚"], ["37"]], hop="single", chapter="1.9"),
    _c("阿德勒与乌尔里希同属哪座岛屿的故事？", "阿派朗岛（Apeiron，孤独之歌）",
       [["Adler"], ["Ulrich", "乌尔里希"]], hop="single", chapter="1.9"),
    _c("Six 与 37 同属哪座岛屿的故事？", "阿派朗岛（Apeiron，孤独之歌）",
       [["Six"], ["37"]], hop="single", chapter="1.9"),
    _c("苏菲亚接手的重塑之手与阿尔卡纳的关系是？", "阿尔卡纳的继任者",
       [["Sophia", "苏菲亚"], ["Arcana", "阿尔卡纳"]],
       hop="single", chapter="其他"),
    _c("勿忘我与斯奈德同属哪一年的芝加哥故事？", "1929 年（第一章芝加哥事件）",
       [["Forget", "勿忘我"], ["Snyder", "斯奈德"]],
       hop="single", chapter="其他"),
    # —— reasoning/temporal 单组浅层补充（medium/shallow/single 结构位）——
    _c("结合“老伙计”与“经验丰富的猎人”两个称呼，这位角色是谁？",
       "Shamane（沙曼）",
       [["Shamane"]], type_="reasoning", chapter="1.4"),
    _c("既管理灯塔又保管档案钥匙的女性是谁？",
       "Zanetta（扎内塔）",
       [["Zanetta"]], type_="reasoning", chapter="1.4"),
    _c("以“雾女士”著称的伦敦女巫是谁？",
       "薇洛（Willow，真名 Charlotte O'Hagan）",
       [["Charlotte", "fog lady", "Willow"]],
       type_="reasoning", chapter="1.4"),
    _c("把记忆化作飞蛾、循光传递情报的能力属于谁的神秘术？",
       "无名者（Ms. Stranger，趋光性）",
       [["moth", "蛾"]], type_="reasoning", chapter="其他"),
    _c("雷米特杯失窃案发生在哪一年？",
       "1966 年（伦敦）",
       [["1966"]], type_="temporal", chapter="其他"),
    _c("1966 年的伦敦发生了哪起震惊世界的失窃案？",
       "雷米特杯失窃案",
       [["1966"]], type_="temporal", chapter="其他"),
    _c("维尔汀首次登场的年份是哪一年？",
       "1966 年",
       [["1966"]], type_="temporal", chapter="其他"),
    _c("77 号往事里淑女格蕾丝主持的行动代号与哪条公路有关？",
       "77 号公路",
       [["Grace", "格蕾丝"], ["77"]],
       hop="single", chapter="其他"),
    _c("同时身为基金会副会长与无名者养母的角色是谁？",
       "康斯坦丁（Constantine）",
       [["Constantine", "康斯坦丁"]], type_="reasoning", chapter="其他"),
    _c("被重塑之手各分支尊为“受苦者”的首领是谁？",
       "阿尔卡纳（Arcana）",
       [["Arcana", "阿尔卡纳"]], type_="reasoning", chapter="其他"),
    _c("既能免疫暴雨又能带人穿越时代的唯一司辰是谁？",
       "维尔汀（Vertin）",
       [["Vertin", "Timekeeper", "维尔汀"]],
       type_="reasoning", chapter="其他"),
]


# ── 2c. 场景组补充 ─────────────────────────────────────────────────────────
# 给部分单组事实题补上题干场景限定组（组内词均经语料命中预检），
# 使其成为「场景定位 + 答案定位」的两级检索题（2 组 → hop 推导为 multi）。
SCENARIO_ADD: dict[str, list[str]] = {
    "阿德勒的英文名是什么？（孤独之歌篇）": ["Apeiron", "阿派朗"],
    "孤独之歌篇里出现的露西的英文名是什么？": ["Apeiron", "阿派朗"],
    "孤独之歌篇里阿派朗岛的研究者乌尔里希的英文名是什么？": ["37"],
    "阿尔卡纳最终死于哪种轰炸武器？": ["Manus", "重塑之手"],
    "维尔汀在阿派朗岛击败阿尔卡纳之后获得的、能庇护更多人的道具是什么？": ["Apeiron", "阿派朗"],
    "37 的同伴中，以数字六为名的少女叫什么？": ["Apeiron", "阿派朗"],
    "阿派朗岛上的时间停滞在哪一年？": ["37"],
    "今夜星光灿烂篇的故事发生在哪座城市？": ["Kakania", "卡卡尼亚"],
    "今夜星光灿烂篇里的年轻调查员马库斯的英文名是什么？": ["Vienna", "维也纳"],
    "特奥菲尔的英文名是什么？（维也纳篇）": ["Vienna", "维也纳"],
    "格蕾塔·霍夫曼的英文名是什么？（今夜星光灿烂篇）": ["Vienna", "维也纳"],
    "多里斯医生的英文名是什么？": ["Vienna", "维也纳"],
    "卡卡尼亚的英文名是什么？": ["Vienna", "维也纳"],
    "海因里希的英文名是什么？": ["Isolde", "伊索尔德"],
    "伊索尔德的英文名是什么？": ["Heinrich", "海因里希"],
    "施瓦茨的英文名是什么？": ["Vienna", "维也纳"],
    "维也纳的英文叫什么？": ["Kakania", "卡卡尼亚"],
    "绿湖噩梦中痴迷恐怖片的男孩的英文名是什么？": ["Green Lake", "camp"],
    "洁西卡的英文名是什么？（绿湖噩梦篇）": ["Green Lake", "camp"],
    "迈克尔的英文名是什么？（绿湖噩梦篇）": ["Green Lake", "camp"],
    "弗莱迪的英文名是什么？（绿湖噩梦篇）": ["Green Lake", "camp"],
    "冷周六的英文名是什么？（绿湖噩梦篇登场角色）": ["Green Lake", "camp"],
    "绿湖噩梦篇的故事发生地是哪个营地？": ["troll", "巨怪"],
    "绿湖噩梦篇的故事发生在哪一年？": ["Green Lake", "camp"],
    "洞穴的囚徒篇里海盗船上的歌手是谁？": ["Sotheby", "苏芙比"],
    "洞穴的囚徒篇中被称作 standkeeper 的女性是谁？": ["Rockin"],
    "洞穴的囚徒篇里名为 Zero 的角色对应数字几？": ["Regulus", "星锑"],
    "雷米特杯失窃案里留下名片的大盗是谁？": ["Pickles"],
    "雷米特杯失窃案里协助找回奖杯的侦探狗是谁？": ["Melania"],
    "77 号往事中被误当作材料处置的农场女孩是谁？": ["Grace", "格蕾丝"],
    "诺谛卡的英文名是什么？": ["Antarctica", "南极"],
    "苏芙比的英文名是什么？": ["Regulus", "星锑"],
    "星锑的英文名是什么？": ["Sotheby", "苏芙比"],
    "玛蒂尔达的英文名是什么？": ["Sonnet", "十四行诗"],
}

for _cand in SEEDS + HAND:
    _extra = SCENARIO_ADD.get(_cand["q"])
    if _extra and len(_cand["evidence"]) == 1:
        _cand["evidence"].append(_extra)


# ── 3. AUTO：别名表自动生成（中→英译名题）────────────────────────────────────

STOP_ALIASES = {
    "he", "she", "it", "i", "me", "my", "you", "your", "yours", "her", "hers",
    "him", "his", "they", "them", "their", "we", "us", "our", "kid", "sir",
    "madam", "master", "child", "boy", "girl", "lady", "man", "woman", "one",
    "two", "all", "who", "what", "and", "the", "for", "with", "that", "this",
    "from", "are", "was", "not", "but", "yes", "no", "okay", "hello", "him?",
    "thing", "anything", "something", "someone", "anyone", "everyone",
    "friend", "friends", "people", "captain", "mister", "miss", "ms", "mr",
}

# seed 已覆盖的事实正名（避免自动题与 seed 重复问同一事实）
SEED_ANSWER_WORDS = {
    "charlotte", "mercuria", "paulina", "ramirez", "noire", "komala",
    "amalfitano", "clara", "schwartz", "heinrich", "isolde", "barcarola",
    "fatutu", "toa", "salone", "kamuta", "aleph", "ulu",
}
SEED_CANONICALS = {"环状水星", "保利娜", "梅兰妮", "卡卡尼亚", "芭卡洛儿",
                   "阿莱夫", "海因里希", "伊索尔德", "薇洛", "可燃点"}

AUTO_TEMPLATES = [
    "「{cn}」的英文名是什么？",                                   # short
    "「{cn}」对应的英文原文是什么？",                             # short
    "在英文剧情语料里，「{cn}」被写作什么？",                     # medium
    "《重返未来：1999》剧情转写里「{cn}」的英文写法是什么？",     # medium/long
    "在《重返未来：1999》的英文剧情与语音转写里，「{cn}」这个名字写作什么？",  # long
]


def _latin_alias(a: str) -> str | None:
    """过滤别名表中的代词/单字/带问号/The 前缀噪声，返回干净英文名。"""
    a = a.strip().rstrip("?？.。!！").strip()
    if len(a) < 3 or "?" in a or "？" in a or "," in a:
        return None
    if not re.fullmatch(r"[A-Za-zÀ-ÖØ-öø-ÿ’' .\-]+", a):
        return None
    low = a.lower()
    if low in STOP_ALIASES:
        return None
    if low.startswith("the "):
        a = a[4:].strip()
        if len(a) < 3:
            return None
    return a


def _auto_alias_candidates() -> list[dict]:
    """读 plot_aliases.json，为每个中文正名生成一道中→英译名题。"""
    path = ROOT / "data" / "lore" / "wu_ming_zhe" / "plot_aliases.json"
    if not path.exists():
        return []
    table = json.loads(path.read_text(encoding="utf-8"))
    out: list[dict] = []
    idx = 0
    for cn, aliases in table.items():
        if not re.search(r"[\u4e00-\u9fff]", cn):
            continue  # 正名不是中文，跳过
        if cn in SEED_CANONICALS:
            continue
        latin = []
        seen = set()
        for a in aliases:
            la = _latin_alias(a)
            if la and la.lower() not in seen:
                seen.add(la.lower())
                latin.append(la)
        if not latin:
            continue
        if any(la.lower() in SEED_ANSWER_WORDS or
               any(la.lower().startswith(w) for w in SEED_ANSWER_WORDS)
               for la in latin):
            continue  # 与 seed 答案重复的事实，跳过
        tpl = AUTO_TEMPLATES[idx % len(AUTO_TEMPLATES)]
        idx += 1
        q = tpl.format(cn=cn, en=latin[0])
        ref = f"{latin[0]}（{cn}）"
        out.append(_c(q, ref, [latin]))
    return out


# ── 汇总候选池 ─────────────────────────────────────────────────────────────

def _build() -> list[dict]:
    pool = SEEDS + HAND + _auto_alias_candidates()
    seen: set[str] = set()
    uniq: list[dict] = []
    for c in pool:
        if c["q"] in seen:
            continue
        seen.add(c["q"])
        uniq.append(c)
    return uniq


CANDIDATES: list[dict] = _build()

if __name__ == "__main__":
    from collections import Counter
    print(f"候选题总数：{len(CANDIDATES)}")
    print("type 分布：", dict(Counter(c["dims"]["type"] for c in CANDIDATES)))
    # 候选题的 hop/difficulty/depth 是**可选项**（由 gen_rag_testset_300.fill_dims 在选题阶段
    # 补齐），池子里多数条目没有这三个键。旧写法 c["dims"]["hop"] 会直接 KeyError 崩掉，
    # 让这个自检入口形同虚设——用 .get 兜底成 "未标注"。
    print("hop 分布：", dict(Counter(c["dims"].get("hop", "未标注") for c in CANDIDATES)))
    print("difficulty 分布：", dict(Counter(c["dims"].get("difficulty", "未标注") for c in CANDIDATES)))
    print("depth 分布：", dict(Counter(c["dims"].get("depth", "未标注") for c in CANDIDATES)))
    print("chapter 分布：", dict(Counter(c["dims"]["chapter"] for c in CANDIDATES)))
